name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build the binary
        run: |
          go build -o server ./...
          ls -l server

      - name: Run unit tests
        run: go test ./... -v

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: transcode-handler-binary
          path: src/transcode-handler